### ISSUE TITLE
not run

### ISSUE THREAD

**Issue by dovahkinnn** [ntaraujo/kivy-easier#1]
[root@DESKTOP-MP8900V ~]# cd C:\Users\hakan\Documents\KivyHelloWorld
-bash: cd: C:UsershakanDocumentsKivyHelloWorld: No such file or directory

**Comment by ntaraujo** [comment]
try in PowerShell or the windows command prompt
if you really need to use in bash, use the linux path syntax: `/mnt/c/Users/hakan/Documents/KivyHelloWorld`
